steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - services/fat-identity-hono/Dockerfile
    env:
      # Enable Docker BuildKit for faster builds
      - DOCKER_BUILDKIT=1
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,short-sha=$SHORT_SHA
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--revision-suffix=commit-$SHORT_SHA'
    id: Deploy
    entrypoint: gcloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update-traffic
      - $_SERVICE_NAME
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--to-revisions=$_SERVICE_NAME-commit-$SHORT_SHA=100'
    entrypoint: gcloud
    id: UpdateTraffic

images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TRIGGER_ID: ad037f34-04e2-45de-9b38-67ce0c0ab382
  _AR_HOSTNAME: europe-west3-docker.pkg.dev
  _PLATFORM: managed
  _SERVICE_NAME: fat-identity-hono
  _DEPLOY_REGION: europe-west3

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - fat-identity-hono
