name: Cleanup Deployment Preview

on:
  pull_request:
    types: [closed]

jobs:
  determine_services:
    name: Determine Affected Services
    runs-on: ubuntu-latest
    
    outputs:
      matrix: ${{ steps.prepare.outputs.json }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Get Changed Files
        id: get_changed_files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }})
          echo "$CHANGED_FILES" > changed_files.txt

      - name: Determine Affected Services
        id: determine
        run: |
          SERVICES_COUNT=$(yq e '.services | length' .github/preview-deployments.config.yml || echo 0)
          for i in $(seq 0 $((SERVICES_COUNT - 1))); do
            if grep -q "^$(yq e ".services[$i].path" .github/preview-deployments.config.yml)" changed_files.txt; then
              echo "service=$(yq e ".services[$i].name" .github/preview-deployments.config.yml)" >> $GITHUB_OUTPUT
              echo "project_id=$(yq e ".services[$i].project_id" .github/preview-deployments.config.yml)" >> $GITHUB_OUTPUT
              echo "region=$(yq e ".services[$i].region" .github/preview-deployments.config.yml)" >> $GITHUB_OUTPUT
              echo "sa_key_secret_name=$(yq e ".services[$i].sa_key_secret_name" .github/preview-deployments.config.yml)" >> $GITHUB_OUTPUT
            fi
          done
      
      # See: https://stackoverflow.com/a/69169075
      - name: Prepare matrix JSON Object
        id: prepare
        uses: nickofthyme/object-remap@v2.0.0
        with:
          __case: snake
          # Feel free to ignore the errors here, the key-values are dynamic
          service: ${{ steps.determine.outputs.service }}
          project_id: ${{ steps.determine.outputs.project_id }}
          region: ${{ steps.determine.outputs.region }}
          sa_key_secret_name: ${{ steps.determine.outputs.sa_key_secret_name }}

      - name: Debug the matrix outputs
        run: |
          echo "Matrix: ${{ steps.prepare.outputs.json }}"
          echo "fromJson: ${{ fromJson(steps.prepare.outputs.json) }}"

  cleanup:
    name: Cleanup Services
    needs: determine_services
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.determine_services.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ matrix.project_id }}
          credentials_json: ${{ secrets[matrix.sa_key_secret_name] }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ matrix.project_id }}

      - name: Remove Cloud Run Tag
        run: |
          gcloud run services update-traffic ${{ matrix.service }} \
            --region=${{ matrix.region }} \
            --remove-tags=pr-${{ github.event.pull_request.number }}
