name: Cleanup Cloud Run PR Environment

on:
  pull_request:
    types: [closed]

env:
  PROJECT_ID: fat-core-dev
  DEPLOY_REGION: europe-west3
  SERVICE_NAME: fat-identity-hono

jobs:
  cleanup:
    name: Cleanup Cloud Run PR Environment
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

          
      - name: Remove Cloud Run Tag
        run: |
          gcloud run services update-traffic ${{ env.SERVICE_NAME }} \
            --region=${{ env.DEPLOY_REGION }} \
            --remove-tags=pr-${{ github.event.pull_request.number }}
