name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-
  test-build:
    name: Test build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Test the build
        run: pnpm run build
