name: Test Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: pnpm/action-setup@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Cache firebase emulators
        uses: actions/cache@v4
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-firebase-emulators-
      - name: Run tests
        run: pnpm test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  build:
    name: Test build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5
      - uses: pnpm/action-setup@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test the build
        run: pnpm build
